import json

notebook_path = 'Analisis_FBG_PEEK6_3sensores_20260721_20mK.ipynb'
with open(notebook_path, 'r') as f:
    nb = json.load(f)

# === Markdown cell: Theory ===
theory_md = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Apéndice A: Estudio Preliminar de Desacoplamiento Strain–Temperatura por Birrefringencia\n",
        "\n",
        "### Motivación\n",
        "\n",
        "Cada sensor FBG produce dos picos de Bragg correspondientes a las dos polarizaciones ortogonales (P y S) de la fibra. Dado que la temperatura y la deformación mecánica (strain) afectan de forma diferente a cada polarización, es posible — en principio — **desacoplar ambos efectos** midiendo las dos longitudes de onda simultáneamente.\n",
        "\n",
        "### Formulación Matricial\n",
        "\n",
        "Cada polarización responde tanto a temperatura ($\\Delta T$) como a strain longitudinal ($\\Delta \\varepsilon$):\n",
        "\n",
        "$$\\begin{pmatrix} \\Delta\\lambda_P \\\\ \\Delta\\lambda_S \\end{pmatrix} = \\begin{pmatrix} K_T^P & K_\\varepsilon^P \\\\ K_T^S & K_\\varepsilon^S \\end{pmatrix} \\begin{pmatrix} \\Delta T \\\\ \\Delta\\varepsilon \\end{pmatrix}$$\n",
        "\n",
        "donde $K_T^{P,S}$ son las sensibilidades térmicas (pm/K) y $K_\\varepsilon^{P,S}$ son las sensibilidades al strain (pm/$\\mu\\varepsilon$) de cada polarización.\n",
        "\n",
        "Si la **matriz de sensibilidades** $\\mathbf{K}$ es invertible ($\\det(\\mathbf{K}) \\neq 0$), podemos resolver:\n",
        "\n",
        "$$\\begin{pmatrix} \\Delta T \\\\ \\Delta\\varepsilon \\end{pmatrix} = \\mathbf{K}^{-1} \\begin{pmatrix} \\Delta\\lambda_P \\\\ \\Delta\\lambda_S \\end{pmatrix}$$\n",
        "\n",
        "### Propiedades clave\n",
        "\n",
        "| Efecto | $\\Delta\\lambda_P$ | $\\Delta\\lambda_S$ | Diferencia $\\Delta\\lambda_P - \\Delta\\lambda_S$ |\n",
        "|--------|-------------------|-------------------|-------------------------------------------------|\n",
        "| Temperatura pura | $K_T^P \\cdot \\Delta T$ | $K_T^S \\cdot \\Delta T \\approx K_T^P \\cdot \\Delta T$ | $\\approx 0$ (efecto isótropo) |\n",
        "| Strain puro | $K_\\varepsilon^P \\cdot \\Delta\\varepsilon$ | $K_\\varepsilon^S \\cdot \\Delta\\varepsilon$ | $\\neq 0$ (efecto anisótropo) |\n",
        "\n",
        "Por tanto, la **diferencia entre polarizaciones** ($\\Delta\\lambda_P - \\Delta\\lambda_S$) es un indicador de strain que, en teoría, es insensible a temperatura.\n",
        "\n",
        "### Limitaciones de este estudio preliminar\n",
        "\n",
        "1. **No disponemos de los coeficientes $K_\\varepsilon^{P,S}$ calibrados** para esta fibra PEEK-6. Sin ellos, no podemos invertir la matriz $\\mathbf{K}$ y obtener $\\Delta T$ y $\\Delta\\varepsilon$ por separado.\n",
        "2. **El coating PEEK** tiene una expansión térmica (~50 ppm/K) mucho mayor que la sílice (~0.5 ppm/K), lo que puede generar **strain inducido por temperatura** que contamina la diferencia P$-$S.\n",
        "3. **La fibra está enrollada**, no tensada. El strain principal es de curvatura constante, no axial.\n",
        "\n",
        "### Qué podemos hacer ahora\n",
        "\n",
        "Un análisis **cualitativo** comparando las polarizaciones P y S:\n",
        "- Si $\\Delta\\lambda_P - \\Delta\\lambda_S$ es constante durante el pico de presión: el evento es **puramente térmico**.\n",
        "- Si cambia durante el pico: hay una **componente de strain** (posible deformación de la cápsula).\n",
        "\n",
        "### Para un análisis riguroso futuro\n",
        "\n",
        "Se necesitaría un experimento de calibración con:\n",
        "1. **Rampas de temperatura a strain constante** (fibra libre) $\\rightarrow$ obtener $K_T^P$ y $K_T^S$.\n",
        "2. **Aplicación de strain controlado a $T$ constante** $\\rightarrow$ obtener $K_\\varepsilon^P$ y $K_\\varepsilon^S$.\n",
        "3. Con los 4 coeficientes, invertir $\\mathbf{K}$ y desacoplar en tiempo real.\n",
    ]
}

# === Code cell: Preliminary analysis ===
code_lines = [
    "import matplotlib\n",
    "# ==============================================================================\n",
    "# APÉNDICE A: Análisis preliminar de birrefringencia P vs S\n",
    "# ==============================================================================\n",
    "\n",
    "DOWNSAMPLE_SEC_A = 2.0\n",
    "t_start_A = datetime.datetime.combine(fecha, datetime.time(15, 30))\n",
    "t_end_A = datetime.datetime.combine(fecha, datetime.time(19, 15))\n",
    "t_plateau_i_A = datetime.datetime.combine(fecha, datetime.time(15, 40))\n",
    "t_plateau_f_A = datetime.datetime.combine(fecha, datetime.time(16, 20))\n",
    "t_peak_i_A = datetime.datetime.combine(fecha, datetime.time(16, 25))\n",
    "t_peak_f_A = datetime.datetime.combine(fecha, datetime.time(17, 5))\n",
    "\n",
    "colors_A = {1: 'red', 2: 'blue', 3: 'green'}\n",
    "\n",
    "# --- Process each polarization separately ---\n",
    "pol_data = {}  # {sensor_num: {'P': {'times', 'wav'}, 'S': {'times', 'wav'}, 'diff': ...}}\n",
    "\n",
    "for sn in [1, 2, 3]:\n",
    "    si = sn - 1\n",
    "    pol_data[sn] = {}\n",
    "    \n",
    "    for pol_idx, pol_name in [(0, 'P'), (1, 'S')]:\n",
    "        w = wav_raw[:, pol_idx, si]\n",
    "        mask_w = (w > 0) & (times_peak >= t_start_A) & (times_peak <= t_end_A)\n",
    "        t_sec = np.array([(t - t_start_A).total_seconds() for t in times_peak[mask_w]])\n",
    "        w_filt = w[mask_w]\n",
    "        \n",
    "        # Downsample\n",
    "        dur = (t_end_A - t_start_A).total_seconds()\n",
    "        be = np.arange(0, dur + DOWNSAMPLE_SEC_A, DOWNSAMPLE_SEC_A)\n",
    "        bc = be[:-1] + DOWNSAMPLE_SEC_A / 2.0\n",
    "        bm, _, _ = stats.binned_statistic(t_sec, w_filt, statistic='mean', bins=be)\n",
    "        vb = ~np.isnan(bm)\n",
    "        tds = np.array([t_start_A + datetime.timedelta(seconds=float(s)) for s in bc[vb]])\n",
    "        wds = bm[vb]\n",
    "        \n",
    "        # Reference wavelength in plateau\n",
    "        mask_bl = (tds >= t_plateau_i_A) & (tds <= t_plateau_f_A)\n",
    "        w0 = np.mean(wds[mask_bl])\n",
    "        \n",
    "        pol_data[sn][pol_name] = {\n",
    "            'times': tds,\n",
    "            'wav_nm': wds,\n",
    "            'dw_pm': (wds - w0) * 1000,  # Variation in pm\n",
    "            'w0': w0,\n",
    "        }\n",
    "    \n",
    "    # Birefringence: difference P - S (aligned to common time grid)\n",
    "    # Both should have same time grid after downsampling\n",
    "    tp = pol_data[sn]['P']['times']\n",
    "    ts = pol_data[sn]['S']['times']\n",
    "    # Use the shorter array and interpolate\n",
    "    t_common_sec_p = np.array([(t - t_start_A).total_seconds() for t in tp])\n",
    "    t_common_sec_s = np.array([(t - t_start_A).total_seconds() for t in ts])\n",
    "    dw_s_interp = np.interp(t_common_sec_p, t_common_sec_s, pol_data[sn]['S']['dw_pm'])\n",
    "    \n",
    "    pol_data[sn]['diff_pm'] = pol_data[sn]['P']['dw_pm'] - dw_s_interp\n",
    "    pol_data[sn]['times_common'] = tp\n",
    "\n",
    "# ==============================================================================\n",
    "# PLOT: 3 panels\n",
    "# ==============================================================================\n",
    "fig, axes = plt.subplots(3, 1, figsize=(16, 12), sharex=True)\n",
    "\n",
    "# --- Panel A: P and S wavelength variation for all 3 FBGs ---\n",
    "ax = axes[0]\n",
    "for sn in [1, 2, 3]:\n",
    "    ax.plot(pol_data[sn]['P']['times'], pol_data[sn]['P']['dw_pm'],\n",
    "            color=colors_A[sn], linewidth=0.6, alpha=0.7,\n",
    "            label=f'FBG-{sn} Pol. P')\n",
    "    ax.plot(pol_data[sn]['S']['times'], pol_data[sn]['S']['dw_pm'],\n",
    "            color=colors_A[sn], linewidth=0.6, alpha=0.4, linestyle='--',\n",
    "            label=f'FBG-{sn} Pol. S')\n",
    "\n",
    "ax.axvspan(t_plateau_i_A, t_plateau_f_A, color='gray', alpha=0.1)\n",
    "ax.axvspan(t_peak_i_A, t_peak_f_A, color='orange', alpha=0.1)\n",
    "ax.set_ylabel('Variacion wavelength (pm)', fontsize=10)\n",
    "ax.set_title('A) Polarizaciones P (continua) y S (discontinua) de cada FBG', fontsize=11, fontweight='bold')\n",
    "ax.legend(fontsize=7, ncol=3, loc='upper right')\n",
    "ax.grid(True, alpha=0.3)\n",
    "\n",
    "# --- Panel B: Birefringence (P - S) ---\n",
    "ax = axes[1]\n",
    "for sn in [1, 2, 3]:\n",
    "    ax.plot(pol_data[sn]['times_common'], pol_data[sn]['diff_pm'],\n",
    "            color=colors_A[sn], linewidth=0.6, alpha=0.7,\n",
    "            label=f'FBG-{sn}')\n",
    "\n",
    "ax.axvspan(t_plateau_i_A, t_plateau_f_A, color='gray', alpha=0.1)\n",
    "ax.axvspan(t_peak_i_A, t_peak_f_A, color='orange', alpha=0.1)\n",
    "ax.axhline(0, color='black', linewidth=0.5, alpha=0.5)\n",
    "ax.set_ylabel('Birrefringencia P - S (pm)', fontsize=10)\n",
    "ax.set_title('B) Diferencia entre polarizaciones: indicador de strain', fontsize=11, fontweight='bold')\n",
    "ax.legend(fontsize=9)\n",
    "ax.grid(True, alpha=0.3)\n",
    "\n",
    "# --- Panel C: Zoom on birefringence during peak ---\n",
    "ax = axes[2]\n",
    "for sn in [1, 2, 3]:\n",
    "    tc = pol_data[sn]['times_common']\n",
    "    diff = pol_data[sn]['diff_pm']\n",
    "    # Smooth with rolling average for clarity\n",
    "    kernel = 15  # 30 seconds at 2s sampling\n",
    "    diff_smooth = np.convolve(diff, np.ones(kernel)/kernel, mode='same')\n",
    "    mask_zoom = (tc >= t_plateau_i_A) & (tc <= t_peak_f_A)\n",
    "    ax.plot(tc[mask_zoom], diff[mask_zoom], color=colors_A[sn], linewidth=0.3, alpha=0.3)\n",
    "    ax.plot(tc[mask_zoom], diff_smooth[mask_zoom], color=colors_A[sn], linewidth=1.5, alpha=0.8,\n",
    "            label=f'FBG-{sn} (suavizado 30s)')\n",
    "\n",
    "ax.axvspan(t_plateau_i_A, t_plateau_f_A, color='gray', alpha=0.1, label='Plateau')\n",
    "ax.axvspan(t_peak_i_A, t_peak_f_A, color='orange', alpha=0.1, label='Pico de presion')\n",
    "ax.axhline(0, color='black', linewidth=0.5, alpha=0.5)\n",
    "ax.set_ylabel('Birrefringencia P - S (pm)', fontsize=10)\n",
    "ax.set_xlabel('Hora (hh:mm)', fontsize=10)\n",
    "ax.set_title('C) Zoom: Plateau + Pico. Si la birrefringencia cambia durante el pico, hay strain',\n",
    "             fontsize=11, fontweight='bold')\n",
    "ax.legend(fontsize=8, loc='upper right')\n",
    "ax.grid(True, alpha=0.3)\n",
    "ax.xaxis.set_major_formatter(matplotlib.dates.DateFormatter('%H:%M'))\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# --- Numerical summary ---\n",
    "print('=' * 80)\n",
    "print('ANALISIS PRELIMINAR DE BIRREFRINGENCIA P - S')\n",
    "print('=' * 80)\n",
    "print(f'{\"Sensor\":<10} {\"sigma_plat (pm)\":<18} {\"sigma_pico (pm)\":<18} {\"Media_plat (pm)\":<18} {\"Media_pico (pm)\":<18} {\"Cambio?\"}')\n",
    "print('-' * 90)\n",
    "\n",
    "for sn in [1, 2, 3]:\n",
    "    tc = pol_data[sn]['times_common']\n",
    "    diff = pol_data[sn]['diff_pm']\n",
    "    mask_plat = (tc >= t_plateau_i_A) & (tc <= t_plateau_f_A)\n",
    "    mask_peak = (tc >= t_peak_i_A) & (tc <= t_peak_f_A)\n",
    "    \n",
    "    sigma_plat = np.std(diff[mask_plat])\n",
    "    sigma_peak = np.std(diff[mask_peak])\n",
    "    mean_plat = np.mean(diff[mask_plat])\n",
    "    mean_peak = np.mean(diff[mask_peak])\n",
    "    \n",
    "    # Is there a significant change?\n",
    "    delta_mean = abs(mean_peak - mean_plat)\n",
    "    significant = delta_mean > 3 * sigma_plat\n",
    "    tag = 'SI (> 3sigma)' if significant else 'NO'\n",
    "    \n",
    "    print(f'FBG-{sn:<6} {sigma_plat:<18.3f} {sigma_peak:<18.3f} {mean_plat:<18.3f} {mean_peak:<18.3f} {tag}')\n",
    "\n",
    "print(f'\\nInterpretacion:')\n",
    "print(f'  Si la media del pico difiere > 3sigma del plateau --> hay evidencia de strain.')\n",
    "print(f'  Si no --> el evento es predominantemente termico.')\n",
]

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": code_lines
}

# Insert AFTER cell 37 (conclusions) and BEFORE cell 38 (spectrum appendix)
nb['cells'].insert(38, theory_md)
nb['cells'].insert(39, code_cell)

# Update the index in Cell 0 to include Appendix A
src0 = ''.join(nb['cells'][0]['source'])
src0 = src0.replace(
    '**Apéndice:** Plot del espectro individual',
    '**Apéndice A:** Estudio preliminar de birrefringencia (desacoplamiento strain-temperatura)\n\n'
    '**Apéndice B:** Plot del espectro individual'
)
nb['cells'][0]['source'] = [src0]

# Update old spectrum appendix label
src_spec = ''.join(nb['cells'][40]['source'])
src_spec = src_spec.replace('## Apéndice:', '## Apéndice B:')
nb['cells'][40]['source'] = [src_spec]

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Total cells: {len(nb['cells'])}")
print("Inserted: Cell 38 (theory markdown) + Cell 39 (code)")
print("Updated: Cell 0 (index) + Cell 40 (spectrum -> Apéndice B)")
